const ProductTypes = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  UPD_PRODUCT: 'UPD_PRODUCT',
  DLT_PRODUCT: 'DLT_PRODUCT',
  LST_PRODUCT_BY_PAGE: 'LST_PRODUCT_BY_PAGE',
  LST_PRODUCT_BY_TERM: 'LST_PRODUCT_BY_TERM',
  FAIL_PRODUCT: 'FAIL_PRODUCT',
  RESET_PRODUCT: 'RESET_PRODUCT',
  FILTER_PRODUCT_BY_CATEGORY: 'FILTER_PRODUCT_BY_CATEGORY',
  FILTER_PRODUCT_BY_PRICE: 'FILTER_PRODUCT_BY_PRICE',
};

export default ProductTypes;
