const ProductTypes = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  UPD_PRODUCT: 'UPD_PRODUCT',
  DLT_PRODUCT: 'DLT_PRODUCT',
  LST_PRODUCT: 'LST_PRODUCT',
  FAIL_PRODUCT: 'FAIL_PRODUCT',
};

export default ProductTypes;
