const VendorTypes = {
  ADD_VENDOR: 'ADD_VENDOR',
  UPD_VENDOR: 'UPD_VENDOR',
  DLT_VENDOR: 'DLT_VENDOR',
  LST_VENDOR: 'LST_VENDOR',
  LST_PRODUCTS: 'LST_PRODUCTS',
  GET_PRODUCT: 'GET_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  UPD_PRODUCT: 'UPD_PRODUCT',
  DLT_PRODUCT: 'DLT_PRODUCT',
  LGN_VENDOR: 'LGN_VENDOR',
  SGN_VENDOR: 'SGN_VENDOR',
  CRT_VENDOR: 'CRT_VENDOR',
  SND_VENDOR: 'SND_VENDOR',
  ADD_SUCURSAL: 'ADD_SUCURSAL',
};

export default VendorTypes;
